
#ifndef RESOURCE_H
#define RESOURCE_H

#define IDI_MAIN_ICON			101

#define IDBS_COUNT													171

// shield judge

#define IDB_GEOLITE2_CITY_MMDB													102
#define IDB_GUARD_WIN_GUARD_X64_EXE													103
#define IDB_GUARD_WIN_GUARD_X86_EXE													104
#define IDB_GUARD_WIN_UNINST_EXE													105
#define IDB_GUARD_WIN_UPGRADE_GD_TXT													106
#define IDB_GUARD_WIN_X64_AGENT_DLL													107
#define IDB_GUARD_WIN_X64_COMMANDO_EXE													108
#define IDB_GUARD_WIN_X64_EXPORTER_DLL													109
#define IDB_GUARD_WIN_X64_INITIATOR_DLL													110
#define IDB_GUARD_WIN_X64_NT_IMPORTER_DLL													111
#define IDB_GUARD_WIN_X64_RECORDER_EXE													112
#define IDB_GUARD_WIN_X86_AGENT_DLL													113
#define IDB_GUARD_WIN_X86_COMMANDO_EXE													114
#define IDB_GUARD_WIN_X86_EXPORTER_DLL													115
#define IDB_GUARD_WIN_X86_INITIATOR_DLL													116
#define IDB_GUARD_WIN_X86_NT_IMPORTER_DLL													117
#define IDB_GUARD_WIN_X86_RECORDER_EXE													118
#define IDB_MANIFEST_TXT													119

// shield judge lin

#define IDB_AMD64_BEARER_QGENERICBEARER_DLL													120
#define IDB_AMD64_ICONENGINES_QSVGICON_DLL													121
#define IDB_AMD64_IMAGEFORMATS_QGIF_DLL													122
#define IDB_AMD64_IMAGEFORMATS_QICNS_DLL													123
#define IDB_AMD64_IMAGEFORMATS_QICO_DLL													124
#define IDB_AMD64_IMAGEFORMATS_QJPEG_DLL													125
#define IDB_AMD64_IMAGEFORMATS_QSVG_DLL													126
#define IDB_AMD64_IMAGEFORMATS_QTGA_DLL													127
#define IDB_AMD64_IMAGEFORMATS_QTIFF_DLL													128
#define IDB_AMD64_IMAGEFORMATS_QWBMP_DLL													129
#define IDB_AMD64_IMAGEFORMATS_QWEBP_DLL													130
#define IDB_AMD64_LIBGCC_S_DW2_1_DLL													131
#define IDB_AMD64_LIBSTDC___6_DLL													132
#define IDB_AMD64_LIBWINPTHREAD_1_DLL													133
#define IDB_AMD64_MANIFEST_TXT													134
#define IDB_AMD64_OFFICER_EXE													135
#define IDB_AMD64_PLATFORMS_QWINDOWS_DLL													136
#define IDB_AMD64_QT5CORE_DLL													137
#define IDB_AMD64_QT5GUI_DLL													138
#define IDB_AMD64_QT5NETWORK_DLL													139
#define IDB_AMD64_QT5SQL_DLL													140
#define IDB_AMD64_QT5SVG_DLL													141
#define IDB_AMD64_QT5WIDGETS_DLL													142
#define IDB_AMD64_SQLDRIVERS_QSQLITE_DLL													143
#define IDB_AMD64_SQLDRIVERS_QSQLMYSQL_DLL													144
#define IDB_AMD64_SQLDRIVERS_QSQLODBC_DLL													145
#define IDB_AMD64_SQLDRIVERS_QSQLPSQL_DLL													146
#define IDB_AMD64_STYLES_QWINDOWSVISTASTYLE_DLL													147
#define IDB_AMD64_TRANSLATIONS_QT_AR_QM													148
#define IDB_AMD64_TRANSLATIONS_QT_BG_QM													149
#define IDB_AMD64_TRANSLATIONS_QT_CA_QM													150
#define IDB_AMD64_TRANSLATIONS_QT_CS_QM													151
#define IDB_AMD64_TRANSLATIONS_QT_DA_QM													152
#define IDB_AMD64_TRANSLATIONS_QT_DE_QM													153
#define IDB_AMD64_TRANSLATIONS_QT_EN_QM													154
#define IDB_AMD64_TRANSLATIONS_QT_ES_QM													155
#define IDB_AMD64_TRANSLATIONS_QT_FI_QM													156
#define IDB_AMD64_TRANSLATIONS_QT_FR_QM													157
#define IDB_AMD64_TRANSLATIONS_QT_GD_QM													158
#define IDB_AMD64_TRANSLATIONS_QT_HE_QM													159
#define IDB_AMD64_TRANSLATIONS_QT_HU_QM													160
#define IDB_AMD64_TRANSLATIONS_QT_IT_QM													161
#define IDB_AMD64_TRANSLATIONS_QT_JA_QM													162
#define IDB_AMD64_TRANSLATIONS_QT_KO_QM													163
#define IDB_AMD64_TRANSLATIONS_QT_LV_QM													164
#define IDB_AMD64_TRANSLATIONS_QT_PL_QM													165
#define IDB_AMD64_TRANSLATIONS_QT_RU_QM													166
#define IDB_AMD64_TRANSLATIONS_QT_SK_QM													167
#define IDB_AMD64_TRANSLATIONS_QT_UK_QM													168
#define IDB_AMD64_TRANSLATIONS_QT_ZH_TW_QM													169
#define IDB_AMD64_UNINST_EXE													170
#define IDB_X64_BEARER_QGENERICBEARER_DLL													171
#define IDB_X64_ICONENGINES_QSVGICON_DLL													172
#define IDB_X64_IMAGEFORMATS_QGIF_DLL													173
#define IDB_X64_IMAGEFORMATS_QICNS_DLL													174
#define IDB_X64_IMAGEFORMATS_QICO_DLL													175
#define IDB_X64_IMAGEFORMATS_QJPEG_DLL													176
#define IDB_X64_IMAGEFORMATS_QSVG_DLL													177
#define IDB_X64_IMAGEFORMATS_QTGA_DLL													178
#define IDB_X64_IMAGEFORMATS_QTIFF_DLL													179
#define IDB_X64_IMAGEFORMATS_QWBMP_DLL													180
#define IDB_X64_IMAGEFORMATS_QWEBP_DLL													181
#define IDB_X64_LIBGCC_S_DW2_1_DLL													182
#define IDB_X64_LIBSTDC___6_DLL													183
#define IDB_X64_LIBWINPTHREAD_1_DLL													184
#define IDB_X64_MANIFEST_TXT													185
#define IDB_X64_OFFICER_EXE													186
#define IDB_X64_PLATFORMS_QWINDOWS_DLL													187
#define IDB_X64_QT5CORE_DLL													188
#define IDB_X64_QT5GUI_DLL													189
#define IDB_X64_QT5NETWORK_DLL													190
#define IDB_X64_QT5SQL_DLL													191
#define IDB_X64_QT5SVG_DLL													192
#define IDB_X64_QT5WIDGETS_DLL													193
#define IDB_X64_SQLDRIVERS_QSQLITE_DLL													194
#define IDB_X64_SQLDRIVERS_QSQLMYSQL_DLL													195
#define IDB_X64_SQLDRIVERS_QSQLODBC_DLL													196
#define IDB_X64_SQLDRIVERS_QSQLPSQL_DLL													197
#define IDB_X64_STYLES_QWINDOWSVISTASTYLE_DLL													198
#define IDB_X64_TRANSLATIONS_QT_AR_QM													199
#define IDB_X64_TRANSLATIONS_QT_BG_QM													200
#define IDB_X64_TRANSLATIONS_QT_CA_QM													201
#define IDB_X64_TRANSLATIONS_QT_CS_QM													202
#define IDB_X64_TRANSLATIONS_QT_DA_QM													203
#define IDB_X64_TRANSLATIONS_QT_DE_QM													204
#define IDB_X64_TRANSLATIONS_QT_EN_QM													205
#define IDB_X64_TRANSLATIONS_QT_ES_QM													206
#define IDB_X64_TRANSLATIONS_QT_FI_QM													207
#define IDB_X64_TRANSLATIONS_QT_FR_QM													208
#define IDB_X64_TRANSLATIONS_QT_GD_QM													209
#define IDB_X64_TRANSLATIONS_QT_HE_QM													210
#define IDB_X64_TRANSLATIONS_QT_HU_QM													211
#define IDB_X64_TRANSLATIONS_QT_IT_QM													212
#define IDB_X64_TRANSLATIONS_QT_JA_QM													213
#define IDB_X64_TRANSLATIONS_QT_KO_QM													214
#define IDB_X64_TRANSLATIONS_QT_LV_QM													215
#define IDB_X64_TRANSLATIONS_QT_PL_QM													216
#define IDB_X64_TRANSLATIONS_QT_RU_QM													217
#define IDB_X64_TRANSLATIONS_QT_SK_QM													218
#define IDB_X64_TRANSLATIONS_QT_UK_QM													219
#define IDB_X64_TRANSLATIONS_QT_ZH_TW_QM													220
#define IDB_X64_UNINST_EXE													221

// shield judge win

#define IDB_BEARER_QGENERICBEARER_DLL													222
#define IDB_ICONENGINES_QSVGICON_DLL													223
#define IDB_IMAGEFORMATS_QGIF_DLL													224
#define IDB_IMAGEFORMATS_QICNS_DLL													225
#define IDB_IMAGEFORMATS_QICO_DLL													226
#define IDB_IMAGEFORMATS_QJPEG_DLL													227
#define IDB_IMAGEFORMATS_QSVG_DLL													228
#define IDB_IMAGEFORMATS_QTGA_DLL													229
#define IDB_IMAGEFORMATS_QTIFF_DLL													230
#define IDB_IMAGEFORMATS_QWBMP_DLL													231
#define IDB_IMAGEFORMATS_QWEBP_DLL													232
#define IDB_LIBGCC_S_DW2_1_DLL													233
#define IDB_LIBSTDC___6_DLL													234
#define IDB_LIBWINPTHREAD_1_DLL													235
#define IDB_MANIFEST_TXT2													236
#define IDB_OFFICER_EXE													237
#define IDB_PLATFORMS_QWINDOWS_DLL													238
#define IDB_QT5CORE_DLL													239
#define IDB_QT5GUI_DLL													240
#define IDB_QT5NETWORK_DLL													241
#define IDB_QT5SQL_DLL													242
#define IDB_QT5SVG_DLL													243
#define IDB_QT5WIDGETS_DLL1													244
#define IDB_SQLDRIVERS_QSQLITE_DLL													245
#define IDB_SQLDRIVERS_QSQLMYSQL_DLL													246
#define IDB_SQLDRIVERS_QSQLODBC_DLL													247
#define IDB_SQLDRIVERS_QSQLPSQL_DLL													248
#define IDB_STYLES_QWINDOWSVISTASTYLE_DLL													249
#define IDB_TRANSLATIONS_QT_AR_QM													250
#define IDB_TRANSLATIONS_QT_BG_QM													251
#define IDB_TRANSLATIONS_QT_CA_QM													252
#define IDB_TRANSLATIONS_QT_CS_QM													253
#define IDB_TRANSLATIONS_QT_DA_QM													254
#define IDB_TRANSLATIONS_QT_DE_QM													255
#define IDB_TRANSLATIONS_QT_EN_QM													256
#define IDB_TRANSLATIONS_QT_ES_QM													257
#define IDB_TRANSLATIONS_QT_FI_QM													258
#define IDB_TRANSLATIONS_QT_FR_QM													259
#define IDB_TRANSLATIONS_QT_GD_QM													260
#define IDB_TRANSLATIONS_QT_HE_QM													261
#define IDB_TRANSLATIONS_QT_HU_QM													262
#define IDB_TRANSLATIONS_QT_IT_QM													263
#define IDB_TRANSLATIONS_QT_JA_QM													264
#define IDB_TRANSLATIONS_QT_KO_QM													265
#define IDB_TRANSLATIONS_QT_LV_QM													266
#define IDB_TRANSLATIONS_QT_PL_QM													267
#define IDB_TRANSLATIONS_QT_RU_QM													268
#define IDB_TRANSLATIONS_QT_SK_QM													269
#define IDB_TRANSLATIONS_QT_UK_QM													270
#define IDB_TRANSLATIONS_QT_ZH_TW_QM													271
#define IDB_UNINST_EXE													272


#endif

